### ISSUE TITLE
Mosaic Graphical Regressions

### ISSUE THREAD

**Issue by Awakened0** [libretro/Mesen-S#1]
There are a few graphical regressions that 98fe9a85d658dbb3d9dd1aa43b3639cf7efc4713 caused documented on the original archived repo:

https://github.com/SourMesen/Mesen-S/issues/162

https://github.com/SourMesen/Mesen-S/issues/163

I tested these using using a build on the previous commit (1d27867dddb2be7e46278abef2d61c5bc617552a) and they didn't happen. The mosaic commit fixes a pretty [minor issue](https://github.com/SourMesen/Mesen-S/issues/145), so it could probably be reverted unless someone knows how to properly fix it.

I suspect these issues are caused by that commit too, but I don't have a way to quickly test them:

https://github.com/SourMesen/Mesen-S/issues/175

https://github.com/SourMesen/Mesen-S/issues/168

**Comment by Awakened0** [comment]
Built from 56989d162671cfb8fe1720b72eec315ec9e4f844 , tested CT and it's fixed. However, for some reason the Win64 buildbot build still has the problem, even though it looks like it should have built since that commit.

**Comment by ichee** [comment]
Current build on buildbot is properly updated now.

**Comment by Awakened0** [comment]
Looks good, thanks!
